### PR TITLE
core: Fix pragma once typo

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by beaumanvienna** [comment]
Hi Rob, Thanks for this one. I started with this project only yesterday. If you like to help with setting up a Vulkan engine, I would appreciate it. Please advise, I plan on merging it over into gfxRenderEngine. This project here is just temporary, to warm up with Vulkan. Best regards, JC   https://discord.gg/fYPKPU4DpM

**Comment by beaumanvienna** [comment]
@RobLoach I only now remembered/recognized you! We met on the RetroRig project. Long time no see! I see you're working a lot on RetroArch, that's great! I moved to Cali in the meantime. Please be sure to join my Discord above! :-D

**Comment by RobLoach** [comment]
Haha, that's a while ago! Know what happened to the project? I've been following you on the Githubs for a while. Love those rendering engines! Also, watch out for the three headed monkey behind you.

**Comment by beaumanvienna** [comment]
haha

**Comment by beaumanvienna** [comment]
@RobLoach Ok, so an empty window works now and it compiles in the workflow for Linux.

RetroRig was discontinued. I reached out to Mike in '20 but didn't get a reply. 

Are you familiar with Vulkan? I'll be implementing [this tutorial](https://youtu.be/Y9U9IE0gVHA) in the next few days. In the gfxRenderEngine, there is a branch called "Scabb" with a ray tracer. I ordered yesterday a new laptop with an NVidia 3050 RTX, then I'd hope to be able to use Vulkan to render the scenes in real-time.

But do check out the main branch of gfxRenderEngine as well. It has only Mednafen at the moment, but it's still fun to use. If you are on Linux, the old Marley project has five emulator cores...

**Comment by RobLoach** [comment]
> an empty window works now and it compiles in the workflow for Linux.

Nice work! Will try to compile that main branch later on this week :wink: 

> Are you familiar with Vulkan?


I haven't done much with Vulkan outside of just running it and tinkering with the values. Looks like a good video tutorial series you linked. Been wanting to try out [gunslinger](https://github.com/MrFrenik/gunslinger) and [sokol](https://github.com/floooh/sokol), as they kind of abstract the rendering, while still having a similar rendering modal.

**Comment by beaumanvienna** [comment]
@RobLoach Here's a little sample scene: https://streamable.com/p8i069
I'm working on the volcano smoke at the moment. Let me know if you can build it. The Readme.md contains some instructions would you can do with the game engine.

**Pull request merged**
